accounts/urls.py
from django.urls import path
from .views import AccountLoginView, AccountLogoutView, account_view

app_name = 'accounts'

urlpatterns = [
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', account_view, name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='user')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
]

user/urls.py
from django.urls import path
from .views import (upload_file,
                    ListUserView,
                    UpdateUserView,
                    DeleteUserView,
                    DetailUserForm,
                    CreateUserView,
                    export_csv, )

app_name = 'user'

urlpatterns = [
    path('', ListUserView.as_view(), name='list'),
    path('create/', CreateUserView.as_view(), name='create'),
    path('update/<int:pk>/', UpdateUserView.as_view(), name='update'),
    path('detail/<int:pk>/', DetailUserForm.as_view(), name='detail'),
    path('delete/<int:pk>/', DeleteUserView.as_view(), name='delete'),
    path('upload/', upload_file, name='upload'),
    path('export_csv/', export_csv, name='export-csv'),
]

accounts/models.py
from django.db import models

# Create your models here.

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    avatar = models.ImageField()
    created_at = models.DateField(auto_now_add=True)

user/forms.py
from django import forms
from .models import User
import csv
from datetime import datetime
import xmltodict
import re
import urllib.request



class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'password',
            'date_joined',
        ]

        widgets = {
            'date_joined': forms.DateInput(),
        }


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'date_joined',
        ]

        widgets = {
            'date_joined': forms.DateInput(),
        }


class UploadFileForm(forms.Form):
    file = forms.FileField()
    widgets = {
        'file': forms.ClearableFileInput(attrs={
            'multiple': True,
        }),
    }

    def clean_file(self):
        file = self.cleaned_data['file']
        if str(file).endswith('.csv'):
            decoded_file = file.read().decode('utf-8').splitlines()
            csv_file = csv.DictReader(decoded_file)
            for row in csv_file:
                username = re.sub(r'\(.*\)', '', str(row['username']))
                if username and row['password'] and row['date_joined']:
                    try:
                        user = User.objects.create_user(
                            username=username,
                            password=row['password'],
                            date_joined=datetime.fromtimestamp(int(row['date_joined']))
                        )
                        user.save()
                    except:
                        print('User already created')

        elif str(file).endswith('.xml'):
            xml_file = xmltodict.parse(file, process_namespaces=True)['user_list']['user']['users']['user']
            for row in xml_file:
                first_name = re.sub(r"\(.*\)", '', str(row['first_name']))
                last_name = re.sub(r"\(.*\)", '', str(row['last_name']))
                if first_name is not '' and last_name is not '':
                    User.objects.filter(username__icontains=last_name).update(
                        last_name=last_name, first_name=first_name)

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render


class AccountLoginView(LoginView):
    template_name = 'accounts/login.html'


class AccountLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'accounts/logout.html'


@login_required
def account_view(request):
    return render(request, 'accounts/profile.html')

user/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from .forms import UploadFileForm, UserForm, UpdateUserForm
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .models import User
import csv


@login_required
def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            return HttpResponseRedirect(reverse_lazy('user:list'))
    else:
        form = UploadFileForm()
    return render(request, 'user/upload.html', {'form': form})


class ListUserView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'user/list.html'


class CreateUserView(LoginRequiredMixin, CreateView):
    model = User
    template_name = 'user/user_form.html'
    success_url = reverse_lazy('user:list')
    form_class = UserForm


class UpdateUserView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'user/user_form.html'
    success_url = reverse_lazy('user:list')
    form_class = UpdateUserForm


class DetailUserForm(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'user/detail.html'
    context_object_name = 'user'


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'user/delete.html'
    success_url = reverse_lazy('user:list')


def export_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=Users ' + str(datetime.now()) + '.csv'
    writer = csv.writer(response)
    writer.writerow(['Username', 'First_name', 'Last_name', 'Date_joined'])
    users = User.objects.all()

    for user in users:
        writer.writerow([user.username, user.first_name, user.last_name, user.date_joined])

    return response

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
    Login
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
  <input class="btn btn-outline-primary" type="submit" value="Login">
</form>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
Logout
{% endblock %}

{% block content %}

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}Welcome {{ user.first_name }}{% endblock %}
{% block content %}
<div class="row">
<p>
    Hello, {{ user.username }} ({{ user.first_name }} {{ user.last_name }})
you was joined to the company on {{ user.date_joined }}
    </p>
    </div>
{% endblock %}

templates/base.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

</head>
<body>
<div class="container" >
{% include 'navbar.html' %}
</div>
<div class="container mt-5 pt-5" >
    {% block content %}{% endblock %}
</div>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg  sticky-top" style="background-color: #EAFAF1 ">
  <div class="container-fluid">
    {% if not user.is_authenticated %}
  <div>
    Please Login to proceed
  </div>
  {% endif %}
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated and user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'user:detail' user.pk %}">Main Page</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Users
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'user:list' %}">List of users</a></li>
            <li><a class="dropdown-item" href="{% url 'user:create' %}">Create (Manually)</a></li>
            <li><a class="dropdown-item" href="{% url 'user:upload' %}">Create (Upload files)</a></li>
            <li><a class="dropdown-item" href="{% url 'user:export-csv' %}">Export to CSV</a></li>
          </ul>
        </li>
        {% endif %}
        </ul>
    <form class="form-inline my-2 my-lg-0">
        {% if user.is_authenticated %}
        <div class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}"><button class="btn btn-info  btn-block" type="button">Logout</button></a>
        </div>
        {% endif %}
        {% if not user.is_authenticated %}
        <div class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}"><button class="btn btn-info  btn-block" type="button">Login</button></a>
        </div>
        {% endif %}
    </form>
  </div>
</nav>
    </div>
  </div>
</nav>

user/templates/user/delete.html
{% extends 'base.html' %}

{% block title %}
Delete User
{% endblock %}

{% block content %}
    <form method="post">
       {% csrf_token %}
        <table>
            <p>Do you really want to delete User</p>
        </table>
        <input class='btn btn-outline-danger' type="submit" value="Agree">
        <a class='btn btn-outline-success' href="{% url 'user:list' %}">Cancel</a>
    </form>
{% endblock %}

user/templates/user/detail.html
{% extends 'base.html' %}

{% block title %}Welcome {{ user.first_name }}{% endblock %}
{% block content %}
<div class="row">
<p>
    Hello, {{ user.username }} ({{ user.first_name }} {{ user.last_name }})
you was joined to the company on {{ user.date_joined }}
    </p>
    </div>
{% endblock %}

user/templates/user/list.html
{% extends 'base.html' %}

{% block title %}
Welcome
{% endblock %}

{% block content %}
  {% if user.is_authenticated and user.is_superuser%}
<div class="row">
  <table class="table-success  table table-striped">
    <thead>
      <th>Username</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Date Joined</th>
      <th>Update</th>
      <th>Delete</th>
    </thead>
    <tbody>
    {% for user in object_list %}
    <tr>
      <td>{{user.username}}</td>
      <td>{{user.first_name}}</td>
      <td>{{user.last_name}}</td>
      <td>{{user.date_joined}}</td>
      <td><a class="btn btn-outline-primary" href="{% url 'user:update' user.pk %}"><i class="bi bi-pencil-fill"></a></td>
      <td><a class="btn btn-outline-danger" href="{% url 'user:delete' user.pk %}"><i class="bi bi-trash3-fill"></a></td>
      <br>
    </tr>
    </tbody>
    {% endfor %}
  </table>
  {% endif %}
</div>
{% endblock %}

user/templates/user/upload.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
Please first upload .csv file and second .xml <br><br><br>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-outline-primary mt-3" type="submit" value="Submit">
</form>
{% endblock %}

user/templates/user/user_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
Create/Update User
{% endblock %}

{% block content %}
    <div class="col">
        <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class='btn btn-outline-primary' type="submit" value="Submit">
        <a class='btn btn-outline-success' href="{% url 'user:list' %}">Cancel</a>
        </form>
    </div>
{% endblock %}